apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: guestbook
          image: gcr.io/google-samples/gb-frontend:v5
          env:
            - name: ENVIRONMENT
              value: "dev"

